# Generated by Django 4.2.13 on 2024-05-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
